#!/bin/bash

if [ $# -eq 0 ]
then
	echo "No arguments supplied"
	exit
fi

if [ $# -eq 1 ]
then
        rm out.xml
	krun  --parser="java -jar parser/parser.jar" $1 >out.xml
        sed -f scripts/process-output.sed -i".bak" out.xml 
fi

if [ $# -eq 2 ]
then
	echo "Too many arguments supplied"
	exit
fi



